services:
  container:
    image: docker.io/hubioinfows/full_env:latest
    container_name: bioinfolauncher-
    environment:
      - DISABLE_AUTH=true
      - CACHE_DIR=/home/user/cache
      - PROJ_DIR=/home/user/proj
      - GITHUB_PAT=
    volumes:
      - ../projects:/home/user/proj
      - ../../cache:/home/user/cache
    ports:
      - 8080:8080
    command: sleep infinity
    init: true